### PR TITLE
Bugfixes and handling of null values

### PR DESCRIPTION
**Pull request by x0f5c3**
Moved to clap, tried to fix errors coming from the HTTP client and the json deserialization.

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thank you for your work! I don’t maintain this crate anymore. If you consider it useful and want to continue, I can transfer the ownership to you.

**Comment by x0f5c3** [comment]
> Thank you for your work! I don’t maintain this crate anymore. If you consider it useful and want to continue, I can transfer the ownership to you.

I think the crate is useful and could even be expanded, improved etc. So I can take the ownership and maintain this crate in my free time :)

**Comment by IvanUkhov** [comment]
Added you as an admin. What is your username on crates.io?

**Comment by x0f5c3** [comment]
> Added you as an admin. What is your username on crates.io?

I use my github account for my crates.io account so the same I guess

**Comment by IvanUkhov** [comment]
Invited you. Now it is in your control. Good luck! 🙂

**Comment by x0f5c3** [comment]
> Invited you. Now it is in your control. Good luck! 🙂

Thanks

**Comment by IvanUkhov** [comment]
About AppVeyor, you can just move the repo to your account.

**Pull request merged**
